
# The scoreboard title
title: '&b&lEZScore'

lines:
  - '&8&m                 '
  - '&aScoreboard line'
  - '&bAnother scoreboard line'
  - '&8&m                 '

# How often scoreboards should automatically refresh (in ticks)
update-interval: 10